export interface ScaleBarcodeConfig {
  prefix: string; // e.g., "20"
  valueType: 'WEIGHT_GRAMS' | 'PRICE_CENTS';
  codeLength: number; // e.g., 5
  valueLength: number; // e.g., 5
}

export interface ScaleDirectConfig {
  connectionType: 'WEB_SERIAL' | 'SIMULATED';
  baudRate: number; // 9600
  protocol: 'SYSTEL_KRETZ' | 'CONTINUOUS_ASCII';
  autoConnect: boolean;
}

export interface ScaleConfig {
  enabled: boolean;
  mode: 'DIRECT' | 'BARCODE' | 'BOTH';
  directConfig: ScaleDirectConfig;
  barcodeConfig: ScaleBarcodeConfig;
}

export interface ScaleBarcodeResult {
  isScaleBarcode: boolean;
  productCode?: string;
  rawValue?: number;
  weightKg?: number;
  pricePaid?: number;
  valueType?: 'WEIGHT_GRAMS' | 'PRICE_CENTS';
}

export class ScaleService {
  private static serialPort: any = null;
  private static reader: any = null;
  private static isConnected: boolean = false;
  private static lastWeight: number = 0;
  private static listeners: Set<(weight: number, isConnected: boolean) => void> = new Set();

  static isWebSerialSupported(): boolean {
    return typeof window !== 'undefined' && 'serial' in navigator;
  }

  static isScaleConnected(): boolean {
    return this.isConnected;
  }

  static getLastWeight(): number {
    return this.lastWeight;
  }

  static subscribe(callback: (weight: number, isConnected: boolean) => void): () => void {
    this.listeners.add(callback);
    // Notify initial state immediately
    callback(this.lastWeight, this.isConnected);
    return () => {
      this.listeners.delete(callback);
    };
  }

  private static notifyListeners(weight: number, connected: boolean) {
    this.lastWeight = weight;
    this.isConnected = connected;
    this.listeners.forEach(cb => cb(weight, connected));
  }

  /**
   * Interprets an EAN-13 barcode generated by a weighing scale.
   * Standard format: [Prefix 2d][Product Code 5d][Weight or Price 5d][Checksum 1d]
   * Example: 2000105012504 -> Prefix 20, Product 00105, Weight 01250g (1.250kg)
   */
  static parseBarcode(scannedBarcode: string, config: ScaleBarcodeConfig): ScaleBarcodeResult {
    const cleanBarcode = scannedBarcode.trim();
    if (!cleanBarcode || cleanBarcode.length !== 13) {
      return { isScaleBarcode: false };
    }

    const prefix = config.prefix || '20';
    if (!cleanBarcode.startsWith(prefix)) {
      return { isScaleBarcode: false };
    }

    const codeLength = config.codeLength || 5;
    const valueLength = config.valueLength || 5;

    const productCode = cleanBarcode.substring(prefix.length, prefix.length + codeLength);
    const valueStr = cleanBarcode.substring(prefix.length + codeLength, prefix.length + codeLength + valueLength);
    const rawValue = parseInt(valueStr, 10);

    if (isNaN(rawValue)) {
      return { isScaleBarcode: false };
    }

    if (config.valueType === 'PRICE_CENTS') {
      const pricePaid = rawValue / 100;
      return {
        isScaleBarcode: true,
        productCode,
        rawValue,
        pricePaid,
        valueType: 'PRICE_CENTS'
      };
    } else {
      const weightKg = rawValue / 1000;
      return {
        isScaleBarcode: true,
        productCode,
        rawValue,
        weightKg,
        valueType: 'WEIGHT_GRAMS'
      };
    }
  }

  /**
   * Opens connection to a physical serial/USB scale using Web Serial API.
   */
  static async connectDirectScale(baudRate: number = 9600): Promise<{ success: boolean; message: string }> {
    if (!this.isWebSerialSupported()) {
      return {
        success: false,
        message: 'Tu navegador no soporta Web Serial API (se recomienda usar Google Chrome, Microsoft Edge u Opera en PC).'
      };
    }

    try {
      if (this.serialPort) {
        await this.disconnectDirectScale();
      }

      const navSerial = (navigator as any).serial;
      this.serialPort = await navSerial.requestPort();
      await this.serialPort.open({ baudRate });
      this.isConnected = true;
      this.notifyListeners(this.lastWeight, true);

      this.startReadingStream();

      return {
        success: true,
        message: 'Balanza conectada correctamente por puerto COM/USB.'
      };
    } catch (err: any) {
      this.isConnected = false;
      this.notifyListeners(0, false);
      return {
        success: false,
        message: err.message || 'No se pudo abrir el puerto de comunicación de la balanza.'
      };
    }
  }

  private static async startReadingStream() {
    if (!this.serialPort?.readable) return;

    try {
      const textDecoder = new TextDecoderStream();
      this.serialPort.readable.pipeTo(textDecoder.writable);
      this.reader = textDecoder.readable.getReader();

      let buffer = '';

      while (true) {
        const { value, done } = await this.reader.read();
        if (done) break;
        if (value) {
          buffer += value;
          // Parse buffer looking for STX/ETX or numeric string patterns
          const match = buffer.match(/[\x02]?([0-9]+\.[0-9]+|\d{4,6})[\x03\r\n]?/);
          if (match) {
            const raw = match[1];
            let parsedWeight = parseFloat(raw);
            if (!isNaN(parsedWeight)) {
              if (parsedWeight > 100 && !raw.includes('.')) {
                parsedWeight = parsedWeight / 1000;
              }
              this.notifyListeners(parsedWeight, true);
            }
            buffer = '';
          }
        }
      }
    } catch (err) {
      console.error('Error leyendo flujo de balanza:', err);
    } finally {
      if (this.reader) {
        try { this.reader.releaseLock(); } catch (_) {}
      }
    }
  }

  static async disconnectDirectScale() {
    try {
      if (this.reader) {
        await this.reader.cancel();
        this.reader = null;
      }
      if (this.serialPort) {
        await this.serialPort.close();
        this.serialPort = null;
      }
    } catch (e) {
      console.error('Error cerrando puerto de balanza:', e);
    } finally {
      this.isConnected = false;
      this.notifyListeners(0, false);
    }
  }

  /**
   * Generates a realistic mock weight reading for testing or demonstration.
   */
  static simulateReadWeight(): number {
    const weights = [0.450, 0.750, 1.250, 1.500, 2.350, 0.820, 3.120];
    const chosen = weights[Math.floor(Math.random() * weights.length)];
    this.notifyListeners(chosen, true);
    return chosen;
  }
}
